### PR TITLE
Merge "113-improve-and-clean-codebase" into develop

### LINKED ISSUE #113: General improvements and just cleaning up the codebase
**Is your feature request related to a problem? Please describe.**
The NoitaMP codebase isn't very organised, with conflicting naming schemes and styles across different areas. (I've mainly noticed this in the utils files)

**Describe the solution you'd like**
Just going through all the files and cleaning them up. This isn't a major issue so can be easily done on the side.

### PR DESCRIPTION
**Pull request by ofoxsmith**
Might have some minor issues with tests, but I think it is fine.

Resolves #113

### CODE REVIEW

**Comment by Ismoh** [comment]
Thanks for the improvements, but as long as the tests aren't succeeded, I cannot merge it:
```
D:\a\NoitaMP\NoitaMP\LuaJIT-2.0.4\bin\luajit.exe: ...taMP\mods\noita-mp\files\scripts\util\CustomProfiler.lua:13: module 'file_util' not found:
	no field package.preload['file_util']
```
Do you need help on running tests locally?

**Comment by Ismoh** [comment]
Something went wrong with tag creation and changelog update. Need to fix this first. Tests wasn't succesfully

**Comment by Ismoh** [comment]
Version and changelog workflows fixed now.
Now it's about you @ofoxsmith fixing tests, afterwards this PR can be merged!

**Comment by Ismoh** [comment]
Regarding LuaRocks and testing, I wuould suggest to make sure, you commited and pushed all left changes.
Then I would remove repo directory completely, afterwards I would do a checkout, then:
- start from the top of the readme til this https://github.com/Ismoh/NoitaMP/blob/113-improve-and-clean-codebase/.building/README.md#make-use-of-luajit-204
- then luarocks test

**Review by Ismoh — APPROVED** [review]

**Comment by Ismoh** [comment]
I am going to squash and merge it, when `luarocks test` works on your local system @ofoxsmith and when noita.exe is loading NoitaMP. Just give me a shout!

**Review by Ismoh — COMMENTED** [review]
What is `mods/noita-mp/output.txt` ? Binary file?

**Comment by ofoxsmith** [comment]
> What is `mods/noita-mp/output.txt` ? Binary file?

A file I used for testing. I must have accidentally commited it.

**Review by Ismoh — APPROVED** [review]

**Pull request merged**
