### PR TITLE
Add silent os.execute and io.popen

### PR DESCRIPTION
**Pull request by BlueAmulet**
Helps to prevent multiple cmd windows from appearing when starting a game. Designed to mimic the original functions behavior as much as possible.

### CODE REVIEW

**Comment by BlueAmulet** [comment]
Probably needs to be gated behind a is OS Windows check so the Ubuntu unit tests still works.

**Comment by Ismoh** [comment]
> Probably needs to be gated behind a is OS Windows check so the Ubuntu unit tests still works.

Ignore Ubuntu unit test, becausw those are not failing, because of your changes. There is an issue ( #49 ) to fix unit tests. In addition to this, I thought about to get rid of Ubuntu unit tests. Windows should be enough. Going to double check it.

**Comment by Ismoh** [comment]
Going to change base_ref to **48-from-develop** branch, which will contain only one commit of **48-developer-want-to-rework-client-and-server-modulesclasses** all commits.
Is clear and better to see, what was changed.

**Comment by Ismoh** [comment]
Didnt work as expected. Going to merge it now. Thanks a lot!

**Pull request merged**
